### ISSUE TITLE
Feature request: preload files

### ISSUE THREAD

**Issue by bouskdav** [cubiclesoft/jquery-fancyfileuploader#12]
Hi,

would be possible to add a feature, so when one initializes the input some existing files on the server could be displayed?

Thanks, cheers,
David

**Comment by cubiclesoft** [comment]
What about using the `preinit` callback?  Not sure what the use-case here is.

**Comment by bouskdav** [comment]
Could be. But is there an easy way to just pass an object to plugin, so it can display files in table as it does when you upload one?

I mean something similiar to https://stackoverflow.com/questions/15028664/how-to-i-preload-existing-files-and-display-them-in-the-blueimp-upload-table

**Comment by cubiclesoft** [comment]
If you want to display files in a table that are on the server, shouldn't that be done elsewhere in the user interface?  Seems like it would create a rather confusing user experience to show files on the server in the uploader region.

**Comment by cubiclesoft** [comment]
You can now probably use the `postinit` callback and then chuck your object into the settings under a non-conflicting name and then handle injecting whatever you need from there.

**Comment by bouskdav** [comment]
Looks good - I will try and let you know.
