### ISSUE TITLE
uploading only two files issue

### ISSUE THREAD

**Issue by Asifkrishaweb** [cubiclesoft/jquery-fancyfileuploader#21]
Hello,

i want to upload more than 2 doc or pdf files but unable to upload it

Below are my js code for file uploading:

```
$(document).ready(function() {
	var filesList = [];
	$('#files').FancyFileUpload({
		url: "/uploadFile",
		params : {
			_token: $('#create-assignment-form').find('input[name="_token"]').first().val(),
		},
		maxfilesize : 5000000,
		added : function(e, data) {
			this.find('.ff_fileupload_actions button.ff_fileupload_start_upload').click();
      for(var i = 0; i < data.files.length; i++){
        filesList.push(data.files[i].name);
      }
      $('#assignment_files').val(filesList);
		}
	});
	jQuery('.ff_fileupload_dropzone').append('<div class="fileupload_txt">Drag & Drop your files (doc, docx, pdf) <span>or</span><span class="browse_txt">Browse</span></div>')
});
```
```

1623162389 (1).docx
1.75 MB of 1.75 MB | 100%

docx

1623162389 (2).docx
1.75 MB of 1.75 MB | 100%

docx

1623162389 (3).docx
1.75 MB | Starting upload...
```
please help for the same

thank you

**Comment by cubiclesoft** [comment]
I think that's a browser/server-level issue.  You have two simultaneous uploads going and they need to finish first before the browser or server will accept new connections/uploads (i.e. 100% is not actually done).  You need to process the data on the server side and respond before the browser/server continue uploading more files.

**Comment by Asifkrishaweb** [comment]
hello

but when i check in temp folder it's showing 2 files completely uploaded

**Comment by cubiclesoft** [comment]
Your example shows two files at 100%.  That indicates the upload hasn't finished yet.  The file data may be on the server but the server side needs to respond correctly to the widget to mark it as actually finished and then start the next upload.

**Comment by Asifkrishaweb** [comment]
Thank you for the clarification.
it's solved.
