### ISSUE TITLE
How can i call delete file manully and showing files at update time

### ISSUE THREAD

**Issue by Asifkrishaweb** [cubiclesoft/jquery-fancyfileuploader#22]
Hello 

i uploading a file on /temp folder when clicking on a tick upload button but after that if i click delete button that file should be delete from /temp folder, so how can i call that delete button at my own.

and second thing 

how can i show/add already uploaded file at edit time in file preview queue

please help for the same

Thank you so much

**Comment by cubiclesoft** [comment]
The "delete" button just removes the item from the upload list so it doesn't clutter the UI.  It's not intended to be used for removing files from the server.  Your application should track upload completion and update your own UI with such features.

Not sure how one would detect already uploaded files (in general).  A user might have two files that are named the same in different directories and want to upload both.  You could hash the file, send the hash to the server, and the server could respond in the affirmative.  The example in the documentation that shows obtaining a security token could be adapted for the purpose.

By the way, issue trackers are not for Q&A.  They are for reporting bugs and sometimes feature requests.

**Comment by brodrigz** [comment]
[Could be done with this PR](https://github.com/cubiclesoft/jquery-fancyfileuploader/pull/31)
