### ISSUE TITLE
Show new selected file in custom preview box and delete from there

### ISSUE THREAD

**Issue by utsavKrishaweb** [cubiclesoft/jquery-fancyfileuploader#23]
Hello,

In the edit section, I have shown already uploaded files as below:
```
<div class="file-upload-box">
  <input id="thefiles" name="files" type="file" accept=".pdf,.doc,.docx" multiple>
  <div class="ff_fileupload_wrap">
      <div class="ff_fileupload_uploads-box">
	    <div class="ff_fileupload_uploads">
              <ul class="ff_fileupload_queued">
	          <li class="ff_fileupload_preview"></li>
	          <li class="ff_fileupload_summary">
                  <div class="ff_fileupload_filename">filename</div>
	          </li>
	          <li class="ff_fileupload_actions">
		          <button class="ff_fileupload_remove_file" type="button" aria-label="Remove from list"></button>
	          </li>
              </ul>
	   </div>
       </div>
    </div>
</div>
```

But, when I select a new file, It will create a new preview box above the custom-made preview box. I want a newly selected file with the already listed files.
And also want to delete files from here manually.

Thank You.

**Comment by cubiclesoft** [comment]
I don't understand what you are asking for/wanting to do.  The widget injects itself into the DOM.  You can't define your own DOM elements and expect the widget to magically use those.

I believe this is related to #22, so I'm closing this issue as well.

As stated in #22, issue trackers are not for Q&A.  They are for reporting bugs and sometimes feature requests.
