### ISSUE TITLE
nrtwork error

### ISSUE THREAD

**Issue by zeehan805** [cubiclesoft/jquery-fancyfileuploader#24]
i am facing  network error retry in moment  failed to load resource. kindly tell me the possible solution of this error

**Comment by cubiclesoft** [comment]
You need to look at the request to and response from your server in the `Network` tab of `Developer Tools` in your web browser.

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

https://developer.chrome.com/docs/devtools/network/

GitHub issue trackers are not the place to ask for product support.  They are primarily for reporting bugs and the occasional feature request.  Closing this issue.
