### ISSUE TITLE
All files uploaded event?

### ISSUE THREAD

**Issue by joaopaulobraga** [cubiclesoft/jquery-fancyfileuploader#25]
Is there a way where I can run a code after all the uploads were completed?
In my case, I want to refresh or reload the page after all the multiple files have been uploaded.
I searched in the plugin but I was unsuccessful. Please any help is very welcome!

Thank you,

Joao

**Comment by cubiclesoft** [comment]
No such event exists but you can use detection code in an `uploadcompleted` callback function:

```js
uploadcompleted: function(e, data) {
	var active = $('.ff_fileupload_uploading, .ff_fileupload_starting');
	var queued = $('.ff_fileupload_queued');

	if (!active.length && !queued.length)
	{
		window.location.reload();
	}
}
```

That code is similar to how the `beforeunload` handler in the uploader detects uploads that are queued or in progress.

**Comment by joaopaulobraga** [comment]
Thank you very much, ir worked like a charm.
