### ISSUE TITLE
Browser upload: File validation or preview

### ISSUE THREAD

**Issue by elgalu** [cubiclesoft/jquery-fancyfileuploader#5]
We need to create a single page app that will allow uploading huge CSV files (e.g. 4 GB) to S3.

Some basic CSV validation should be in place, at least for first N lines of the file.

If there are errors in the file we would abort the upload and show the validation error to the user.

Is that possible with this library?

**Comment by cubiclesoft** [comment]
I don't see why it wouldn't be possible.

I'm closing this as you've asked a question rather than reporting an actual issue.  There are cheaper and better alternatives to AWS out there.
