### ISSUE TITLE
Network error, retrying in a moment.

### ISSUE THREAD

**Issue by mzhossain** [cubiclesoft/jquery-fancyfileuploader#7]
Hi, it always show Network error, retrying in a moment. is it because upload folder is not assigned anywhere? where do you mention upload folder name? please help. Thanks.

**Comment by cubiclesoft** [comment]
The "Network error, retrying in a moment" message comes from an unexpected server response.  Watch the Network tab in your web browser and look at the response from the server.  This tool expects the server to respond with JSON in a specific format.  Non-JSON responses are an error.
