### ISSUE TITLE
messages translation

### ISSUE THREAD

**Issue by asadghazanfary** [cubiclesoft/jquery-fancyfileuploader#9]
hi

how can translate plugin messages to persian language?

please show me with sample

**Comment by asadghazanfary** [comment]
I have another question:

How can we restrict a user who is not allowed to upload just one more file?

Thanks for answering my questions

**Comment by cubiclesoft** [comment]
Added instructions for creating a translation to the README.

I don't understand the other question.  If you are asking how to limit to uploading a single file, that's more of a UI decision.  The plugin, by default, uploads each file one at a time.  So you can just overwrite what is on the server if you receive another file.
